PSA_forum/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app_homepage.urls')),
    url('^', include('django.contrib.auth.urls')),
    # path('home/', include('app_homepage.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_homepage/urls.py
from django.conf.urls import url

from . import views

app_name = 'app_homepage'

urlpatterns = [
    url(r'^$', views.homepage, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/(?P<profile_name>[\w\-]+)/$', views.otherProfile, name='otherProfile'),
    url(r'^upload/$', views.upload_song, name='upload_song'),
    url(r'^delete/(?P<song_id>[\w\-]+)/$', views.delete_song, name='delete_song'),
    url(r'^playlist/$', views.playlist, name='playlist'),
    url(r'^addSong/(?P<song_id>[\w\-]+)/$', views.addSong, name='addSong'),
    url(r'^removeSong/(?P<song_id>[\w\-]+)/$', views.removeSong, name='removeSong'),
    url(r'^likeSong/(?P<song_id>[\w\-]+)/$', views.likeSong, name='likeSong'),
    url(r'^dislikeSong/(?P<song_id>[\w\-]+)/$', views.dislikeSong, name='dislikeSong'),
    url(r'^editSong/(?P<song_id>[\w\-]+)/$', views.edit_song, name='editSong'),
    url(r'^top5/$', views.topSongs, name='topSongs'),
    url(r'^comments/(?P<song_id>[\w\-]+)/$', views.comments, name='comments'),
    url(r'^genrePage/$', views.genrePage, name='genrePage'),
    url(r'^genrePage/(?P<genre>[\w\-]+)/$', views.displayGenre, name='displayGenre'),
    url(r'^editProfile/$', views.editProfile, name='editProfile'),
]

app_homepage/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User

from django.utils import timezone

GENRES_NAMES = (
    ('Pop', 'Pop'),
    ('Rock', 'Rock'),
    ('House', 'House'),
    ('Hip-Hop', 'Hip-Hop'),
    ('Techno', 'Techno'),
    ('Unknown', 'Unknown'),
)

def file_size(value):  # add this to some file where you can import it from
    limit = 10 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed {} MiB.'.format(limit / 1024 / 1024))


class Song(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    song_author = models.CharField(max_length=200, default='')
    song_title = models.CharField(max_length=200)
    song_genre = models.CharField(max_length=200, default='Unknown', choices=GENRES_NAMES)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    likes = models.ManyToManyField(User, related_name='song_likes', blank=True, null=True)
    song_file = models.FileField(default='', validators=[file_size])
    num_likes = models.IntegerField(default=0)

    def __str__(self):
        return "{}: {} - {} | {}".format(self.user, self.song_author, self.song_title, self.pub_date)


class Playlist(models.Model):
    playlist_user = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    playlist_songs = models.ManyToManyField(Song)
    creation_date = models.DateTimeField('Playlist created', auto_now_add=True)

    def __str__(self):
        return self.playlist_user.username

class Comment(models.Model):
    song = models.ForeignKey(Song, blank=True, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    comment = models.TextField(max_length=120)
    creation_date = models.DateTimeField('Comment date', default=timezone.now)

    def __str__(self):
        return "{}: {}| {}".format(self.user, self.song, self.creation_date)

app_homepage/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from app_homepage.models import *

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username', 'password', 'first_name', 'last_name', 'email']

class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_author', 'song_title', 'song_genre', 'song_file']

class SongEditForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_author', 'song_title', 'song_genre']

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment']

class EditProfile(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

app_homepage/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db.models import Sum, Count, F
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from app_homepage.models import *
from .forms import *

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']

def homepage_parameters(request):
    user_likes = []
    comments = []
    flag = False
    for song in Song.objects.all():
        comments.append(Comment.objects.filter(song=song).count())
        for user in song.likes.all():
            if user == request.user:
                flag = True
                break
        if flag:
            user_likes += ['True']
        else:
            user_likes += ['False']
        flag = False

    return zip(Song.objects.all(), user_likes, comments)

def profile_parameters(request, song_id):
    user_likes = []
    flag = False
    for user in Song.objects.get(song_id).likes.all():
        if user == request.user:
            flag = True
            break
        if flag:
            user_likes += ['True']
        else:
            user_likes += ['False']
        flag = False

    return zip(Song.objects.all(), user_likes)

def homepage(request):
    context = {}
    context['songs'] = homepage_parameters(request)
    context['comments'] = Comment.objects.all()
    return render(request, 'index.html', context)

def profile(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/')
    context = {}
    context['user_info'] = User.objects.get(username=request.user)
    context['songs'] = Song.objects.filter(user__username=request.user)
    context['uploaded_songs'] = Song.objects.filter(user__username=request.user).count()
    # context['user_info'] = User.objects.get(username=request.user)

    try:
        context['playlist'] = Playlist.objects.get(playlist_user=request.user).playlist_songs.all()
    except:
        pass
    return render(request, 'Profile.html', context)

def otherProfile(request, profile_name):
    context = {}
    user = User.objects.get(username__exact=profile_name)
    context['user_info'] = user
    context['songs'] = Song.objects.filter(user__username=user)
    context['uploaded_songs'] = Song.objects.filter(user__username=user).count()
    context['playlist'] = -1
    return render(request, 'Profile.html', context)

def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')

    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                context = {}
                context['songs'] = homepage_parameters(request)
                return render(request, 'index.html', context)
    context = {
        "form": form,
    }
    return render(request, 'registration.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                context = {}
                context['songs'] = homepage_parameters(request)
                return HttpResponseRedirect('/', context)
            else:
                return render(request, 'login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'login.html', {'error_message': 'Invalid login'})
    return render(request, 'login.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'login.html', context)

def upload_song(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/')
    form = SongForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        if len(str(form.cleaned_data['song_author'])) > 60:
            context = {
                'form' : form,
                'error_message': 'Song author field text size cannot be greater than 60 symbols'
            }
            return render(request, 'upload_song.html', context)

        if len(str(form.cleaned_data['song_author'])) > 60:
            context = {
                'form' : form,
                'error_message': 'Song title field text size cannot be greater than 60 symbols'
            }
            return render(request, 'upload_song.html', context)

        song = form.save(commit=False)
        song.song_file = request.FILES['song_file']
        song.song_author = form.cleaned_data['song_author']
        song.song_genre = form.cleaned_data['song_genre']
        song.user = request.user
        file_type = song.song_file.url.split('.')[-1]
        file_type = file_type.lower()

        if file_type not in AUDIO_FILE_TYPES:
            context = {
                'form': form,
                'error_message': 'Audio file must be WAV, MP3, or OGG',
            }
            return render(request, 'upload_song.html', context)

        song.save()
        return redirect('/', {'songs': Song.objects.all()})
    context = {
        'form': form,
    }
    return render(request, 'upload_song.html', context)

def delete_song(request, song_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/')
    context = {}
    song = Song.objects.get(pk=song_id)
    if str(song.user) == str(request.user) or str(request.user) == 'admin':
        song.delete()
    else:
        return HttpResponseRedirect('/')

    context['user_info'] = User.objects.get(username__exact=request.user)
    context['songs'] = Song.objects.filter(user__username=request.user)
    context['uploaded_songs'] = Song.objects.filter(user__username=request.user).count()
    return HttpResponseRedirect('/profile/', context)

def edit_song(request, song_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/')
    song = Song.objects.get(pk=song_id)
    form = SongEditForm(request.POST or None, initial={'song_author': song.song_author, 'song_title': song.song_title, 'song_genre': song.song_genre})
    if form.is_valid():
        song.song_author = form.cleaned_data['song_author']
        song.song_title = form.cleaned_data['song_title']
        song.song_genre = form.cleaned_data['song_genre']
        song.save()

        context = {}
        context['user_info'] = User.objects.get(username__exact=request.user)
        context['songs'] = Song.objects.filter(user__username=request.user)
        context['uploaded_songs'] = Song.objects.filter(user__username=request.user).count()
        try:
            context['playlist'] = Playlist.objects.get(playlist_user=request.user).playlist_songs.all()
        except:
            pass
        return HttpResponseRedirect('/profile/', context)

    context = {
        'form': form,
        'song': song
    }
    return render(request, 'editSong.html', context)

def playlist(request):
    try:
         return render(request, 'Playlist.html', {'playlist': Playlist.objects.get(playlist_user=request.user).playlist_songs.all()})
    except:
        if not request.user.is_authenticated:
            return HttpResponseRedirect('/')
        context = {}
        context['songs'] = Song.objects.filter(user__username=request.user)
        context['uploaded_songs'] = Song.objects.filter(user__username=request.user).count()
        context['Error'] = 'Playlist is not created'
        return HttpResponseRedirect('/profile/', context)

def removeSong(request, song_id):
    context = {}
    song = Song.objects.get(pk=song_id)
    # user = User.objects.get(username=request.user)
    playlist = Playlist.objects.get_or_create(playlist_user=request.user)[0]
    playlist.playlist_songs.remove(song)
    context['playlist'] = Playlist.objects.get(playlist_user=request.user).playlist_songs.all()
    return render(request, 'Playlist.html', context)

def addSong(request, song_id):
    context = {}

    song = Song.objects.get(pk=song_id)
    user = User.objects.get(username=request.user)
    playlist = Playlist.objects.get_or_create(playlist_user=user)[0]
    playlist.playlist_songs.add(song)

    context['songs'] = homepage_parameters(request)
    return render(request, 'index.html', context)

def likeSong(request, song_id):
    context = {}
    song = Song.objects.get(pk=song_id)
    user = User.objects.get(username=request.user)
    song.likes.add(user)
    song.num_likes += 1
    song.save()
    context['songs'] = homepage_parameters(request)
    return render(request, 'index.html', context)

def dislikeSong(request, song_id):
    context = {}
    song = Song.objects.get(pk=song_id)
    user = User.objects.get(username=request.user)
    song.likes.remove(user)
    song.num_likes -= 1
    song.save()
    context['songs'] = homepage_parameters(request)
    return render(request, 'index.html', context)

def topSongs(request):
    context = {}
    context['songs'] = Song.objects.order_by('-num_likes')[:5]
    return render(request, 'topSongs.html', context)

def genrePage(request):
    context = {}
    genres_list = ['Pop', 'Rock', 'House', 'Hip-Hop', 'Techno', 'Unknown']
    genres = []
    genres_count = []
    for genre in genres_list:
        genres.append(genre)
        # results.append(genre + ' ('+ str(Song.objects.filter(song_genre=genre).count())+')')
        genres_count.append(Song.objects.filter(song_genre=genre).count())
    genres_info = zip(genres, genres_count)
    context['genre_list'] = genres_info

templates/Profile.html
{% extends "base_generic.html" %}
{% block title %} Profile {% endblock %}
{% block base_body %}

    <script>
    $(document).ready( function (){
        $('table.display').DataTable();
    } );
    </script>
   <div class="container">
   {% if user_info.username|slugify == user|slugify %}
    <h1>My Profile</h1>
   {% else %}
    <h1>{{ user_info.username }} Profile</h1>
   {% endif %}
    </div>
    <h3>User: {{ user_info.username}}</h3>
    <br>
    <h2>Information about {{ user_info.username }}:</h2>
    <ul>
        {% if user_info.first_name|slugify != '' %}
        <li>First name: {{ user_info.first_name }}</li>
        {% else %}
        <li>First name: This user did not provide this information</li>
        {% endif %}

        {% if user_info.last_name|slugify != '' %}
        <li>Last name: {{ user_info.last_name }}</li>
        {% else %}
        <li>Last name: This user did not provide this information</li>
        {% endif %}

        {% if user_info.email|slugify != '' %}
        <li>Email address: {{ user_info.email }}</li>
        {% else %}
        <li>Email address: This user did not provide this information</li>
        {% endif %}

    </ul>
    {% if user_info.username|slugify == user|slugify %}
        <a href = "{%  url 'app_homepage:editProfile'%}">Edit profile information</a>
    {% endif %}
    <h3> Statistics:</h3>
    <ul>
        <li>Number of songs: {{ uploaded_songs }}</li>
        <li>Number of total likes:  {{ total_likes }}</li>
    </ul>
    {% if songs|length > 0 %}
    <h3>All uploaded songs:</h3>
    <table id="" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Song</th>
            <th>Title</th>
            <th>Genre</th>
            <th>Likes</th>
            <th>Publish date</th>
            <th>Uploaded by</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
     {% for song in songs %}
        <tr>
         <td>
            <a target="_blank" href="{{ song.song_file.url }}">
                <button type="button" class="btn btn-success btn-xs">
                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                </button>
            </a>
        </td>
            <td>{{ song.song_author }} - {{song.song_title}}</td>
            <td>{{ song.song_genre }}</td>
            <td>{{ song.likes.all | length }}</td>
            <td>{{ song.pub_date }}</td>
            <td>{{ song.user }}</td>
            {% if song.user|stringformat:"s" == request.user.username or request.user.username == 'admin' %}
                <td><a href = "{%  url 'app_homepage:editSong' song_id=song.id%}">Edit</a></td>
                <td><a href = "{%  url 'app_homepage:delete_song' song.id %}" onclick="return confirm('Are you sure you want to delete this?')">Delete</a></td>
            {% endif %}
        </tr>
     {% endfor %}
    </tbody>
</table>
    {% else %}
    <h3>User did not upload any song</h3>
    {% endif %}
{% if playlist|length > 0 %}
    <h3>My Playlist:</h3>
        <table id="" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Song</th>
            <th>Title</th>
            <th>Genre</th>
            <th>Likes</th>
            <th>Publish date</th>
            <th>Uploaded by</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
     {% for song in playlist %}
        <tr>
         <td>
            <a target="_blank" href="{{ song.song_file.url }}">
                <button type="button" class="btn btn-success btn-xs">
                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                </button>
            </a>
        </td>
            <td>{{ song.song_author }} - {{song.song_title}}</td>
            <td>{{ song.song_genre }}</td>
            <td>{{ song.likes.all | length}}</td>
            <td>{{ song.pub_date }}</td>
            <td>{{ song.user }}</td>
            {% if song.user|stringformat:"s" == request.user.username or request.user.username == 'admin' %}
            <td><a href = "{%  url 'app_homepage:delete_song' song.id %}">Delete</a></td>
            {% endif %}
        </tr>
     {% endfor %}
    </tbody>
</table>
    {% elif  playlist|length == 0 and playlist != -1%}
        <h2>There are no songs in the playlist</h2>
    {% elif playlist == -1 %}
    {% endif %}
{% endblock %}

templates/app_homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Soundcloud</title>
</head>
<body>
<h1> Homepage </h1>
<h3>All available songs:</h3>
<ul>
    {% for song in songs %}
        <li>{{ song.song_author }} - {{song.song_title}}</li>
        <audio controls="controls">
          <source src="{{ song.song_file.url }}" type="audio/mpeg" />
           <!-- fallback content -->
            Your browser does not support the audio player.
        </audio>
        <p>Likes: {{ song.song_likes }}</p>
        Uploaded by: <a href = '#'>{{ song.user }}</a>
        <p></p>
    {% endfor %}
</ul>

</body>
</html>

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Home{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation     </span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'app_homepage:index' %}">MegaSound</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'app_homepage:index' %}">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'app_homepage:topSongs' %}">TOP 5</a></li>
        <li><a href="{% url 'app_homepage:genrePage' %}">Genres</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          {% if not user.is_authenticated %}
              <li><a href="{% url 'app_homepage:register' %}">Register</a></li>
              <li><a href="{% url 'app_homepage:login' %}">Login</a></li>
          {% endif %}
       {% if user.is_authenticated %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile: {{ user }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'app_homepage:profile' %}">My Profile</a></li>
            <li><a href="{% url 'app_homepage:playlist' %}">My Playlist</a></li>
            <li><a href="{% url 'app_homepage:upload_song' %}">Upload Song</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'app_homepage:logout' %}">Logout</a></li>
          </ul>
        </li>
      {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% block base_body %}
{% endblock %}
</body>
</html>

templates/displayGenre.html
{% extends "base_generic.html" %}
{% block base_body %}

    <script>
    $(document).ready( function (){
    $('#table_id').DataTable({
        "pageLength": 25,
        "order": [[ 4, "desc" ]]
    })
    } );
    </script>

   <div class="container">
    <h1>Homepage</h1>
    </div>

    <h3>All available songs:</h3>
    </ul>
    <table id="table_id" class="display">
    <thead>
        <tr>
            <th>Song</th>
            <th>Title</th>
            <th>Genre</th>
            <th>Likes</th>
            <th>Publish date</th>
            <th>Uploaded by</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
     {% for song, like in songs %}
         <tr>
         <td>
            <a target="_blank" href="{{ song.song_file.url }}">
                <button type="button" class="btn btn-success btn-xs">
                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                </button>
            </a>
        </td>
            <td>{{ song.song_author }} - {{song.song_title}}</td>
            <td>{{ song.song_genre }}</td>
            <td>{{ song.likes.all | length}}</td>
            <td>{{ song.pub_date.year }}-{{ song.pub_date.month }}-{{ song.pub_date.day }} | {{ song.pub_date.hour }}:{{ song.pub_date.minute }}</td>
            <td><a href = "{%  url 'app_homepage:otherProfile' song.user %}">{{ song.user }}</a></td>
            <td>
            {% if user.is_authenticated %}
                    <a href = "{% url 'app_homepage:addSong' song.id%}"> Add to Playlist</a>

                    {% if like == 'False' %}
                        <a href = "{% url 'app_homepage:likeSong' song.id%}"> Like</a>
                    {% else %}
                        <a href = "{% url 'app_homepage:dislikeSong' song.id%}"> Dislike</a>
                    {% endif %}
            {% endif %}
                <a href = "{% url 'app_homepage:comments' song.id%}"> Comments</a>
            </td>
         </tr>
     {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/genrePage.html
{% extends "base_generic.html" %}
{% block title %} Edit Song {% endblock %}
{% block base_body %}
    {% for genre, count in genre_list%}
        <ul><a href="{% url 'app_homepage:displayGenre' genre %}">{{ genre }} ({{ count }})</a></ul>
    {% endfor %}
{% endblock %}

templates/index.html
{% extends "base_generic.html" %}
{% block base_body %}

    <script>
    $(document).ready( function (){
    $('#table_id').DataTable({
        "pageLength": 25,
        "order": [[ 4, "desc" ]]
    })
    } );
    </script>

   <div class="container">
    <h1>Homepage</h1>
    </div>

    <h3>All available songs:</h3>
    </ul>
    <table id="table_id" class="display">
    <thead>
        <tr>
            <th>Song</th>
            <th>Title</th>
            <th>Genre</th>
            <th>Likes</th>
            <th>Publish date</th>
            <th>Uploaded by</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
     {% for song, like, comments_count in songs %}
         <tr>
         <td>
            <a target="_blank" href="{{ song.song_file.url }}">
                <button type="button" class="btn btn-success btn-xs">
                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                </button>
            </a>
        </td>
            <td>{{ song.song_author }} - {{song.song_title}}</td>
            <td>{{ song.song_genre }}</td>
            <td>{{ song.likes.all | length}}</td>
            <td>{{ song.pub_date.year }}-{{ song.pub_date.month }}-{{ song.pub_date.day }} | {{ song.pub_date.hour }}:{{ song.pub_date.minute }}</td>
            <td><a href = "{%  url 'app_homepage:otherProfile' song.user %}">{{ song.user }}</a></td>
            <td>

                {% if user.is_authenticated %}
                    <a href = "{% url 'app_homepage:addSong' song.id%}"> Add to Playlist</a>

                    {% if like == 'False' %}
                        <a href = "{% url 'app_homepage:likeSong' song.id%}"> Like</a>
                    {% else %}
                        <a href = "{% url 'app_homepage:dislikeSong' song.id%}"> Dislike</a>
                    {% endif %}

                {% endif %}

                <a href = "{% url 'app_homepage:comments' song.id%}"> Comments({{ comments_count }})</a>
            </td>
         </tr>
     {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/topSongs.html
{% extends "base_generic.html" %}
{% block base_body %}

    <script>
    $(document).ready( function (){
    $('#table_id').DataTable({
        "pageLength": 5,
    })
    } );
    </script>

   <div class="container">
    <h1>Homepage</h1>
    </div>

    <h3>All available songs: </h3>
    </ul>
    <table id="table_id" class="display">
    <thead>
        <tr>
            <th>Position</th>
            <th>Song</th>
            <th>Title</th>
            <th>Genre</th>
            <th>Likes</th>
            <th>Publish date</th>
            <th>Uploaded by</th>
            {% if user.is_authenticated %}
            <th>Actions</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
     {% for song in songs %}
         <tr>
         <td>TOP {{ forloop.counter }}</td>
         <td>
            <a target="_blank" href="{{ song.song_file.url }}">
                <button type="button" class="btn btn-success btn-xs">
                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                </button>
            </a>
        </td>
            <td>{{ song.song_author }} - {{song.song_title}}</td>
            <td>{{ song.song_genre }}</td>
            <td>{{ song.likes.all | length}}</td>
            <td>{{ song.pub_date.year }}-{{ song.pub_date.month }}-{{ song.pub_date.day }} | {{ song.pub_date.hour }}:{{ song.pub_date.minute }}</td>
            <td><a href = "{%  url 'app_homepage:otherProfile' song.user %}">{{ song.user }}</a></td>
             {% if user.is_authenticated %}
                 <td>
                    <a href = "{% url 'app_homepage:addSong' song.id%}"> Add to Playlist</a>

                    {% if like == 'False' %}
                        <a href = "{% url 'app_homepage:likeSong' song.id%}"> Like</a>
                    {% else %}
                        <a href = "{% url 'app_homepage:dislikeSong' song.id%}"> Dislike</a>
                    {% endif %}
            </td>
            {% endif %}
         </tr>
     {% endfor %}
    </tbody>
</table>
{% endblock %}